# coding=utf-8

WAVE_FORM_PART = 4
WAVE_GRAPH_QUALITY = 2000
PROGRESSION_COLOR = '#D1ED4A'
DOT_EMPTY = 'dotempty.png'
DOT_FULL = 'dotfull.png'

STRUCTURE_GROUP_SPACE = 5
STRUCTURE_LINE_SPACE = 0

BEAT_COLOR_ACTIVE = '#cc0000'
BEAT_COLOR_NORMAL = '#ffffff'
COMMON_COLOR = '#ffffff'

MAIN_VIDEO_CLIP = 'mvc'

SECTION_COLOR_DEFAULT = '#ffffff'
